-- MySQL Script generated by MySQL Workbench
-- Wed Mar  3 20:30:22 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema heroku_c287edf3bb7864d
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `heroku_c287edf3bb7864d` ;

-- -----------------------------------------------------
-- Schema heroku_c287edf3bb7864d
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `heroku_c287edf3bb7864d` DEFAULT CHARACTER SET utf8 ;
USE `heroku_c287edf3bb7864d` ;

-- -----------------------------------------------------
-- Table `heroku_c287edf3bb7864d`.`product_categories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `heroku_c287edf3bb7864d`.`product_categories` ;

CREATE TABLE IF NOT EXISTS `heroku_c287edf3bb7864d`.`product_categories` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  `deleted_at` TIMESTAMP NULL,
  `name` VARCHAR(100) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_copy1_UNIQUE` (`id` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `heroku_c287edf3bb7864d`.`brands`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `heroku_c287edf3bb7864d`.`brands` ;

CREATE TABLE IF NOT EXISTS `heroku_c287edf3bb7864d`.`brands` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  `deleted_at` TIMESTAMP NULL,
  `name` VARCHAR(100) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `heroku_c287edf3bb7864d`.`products`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `heroku_c287edf3bb7864d`.`products` ;

CREATE TABLE IF NOT EXISTS `heroku_c287edf3bb7864d`.`products` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `description` VARCHAR(500) NOT NULL,
  `year` INT NULL,
  `base_price` DECIMAL NULL,
  `discount` INT NULL,
  `final_price` DECIMAL NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  `deleted_at` TIMESTAMP NULL,
  `category_id` BIGINT NULL,
  `brand_id` BIGINT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) ,
  INDEX `category_id_idx` (`category_id` ASC) ,
  INDEX `brand_id_idx` (`brand_id` ASC) ,
  CONSTRAINT `category_id`
    FOREIGN KEY (`category_id`)
    REFERENCES `heroku_c287edf3bb7864d`.`product_categories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `brand_id`
    FOREIGN KEY (`brand_id`)
    REFERENCES `heroku_c287edf3bb7864d`.`brands` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `heroku_c287edf3bb7864d`.`user_categories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `heroku_c287edf3bb7864d`.`user_categories` ;

CREATE TABLE IF NOT EXISTS `heroku_c287edf3bb7864d`.`user_categories` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  `deleted_at` TIMESTAMP NULL,
  `name` VARCHAR(100) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `heroku_c287edf3bb7864d`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `heroku_c287edf3bb7864d`.`users` ;

CREATE TABLE IF NOT EXISTS `heroku_c287edf3bb7864d`.`users` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(100) NOT NULL,
  `last_name` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  `profile_image` VARCHAR(100) NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  `deleted_at` TIMESTAMP NULL,
  `category_id` BIGINT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) ,
  INDEX `category_id_idx` (`category_id` ASC) ,
  CONSTRAINT `user_category_id`
    FOREIGN KEY (`category_id`)
    REFERENCES `heroku_c287edf3bb7864d`.`user_categories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `heroku_c287edf3bb7864d`.`colors`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `heroku_c287edf3bb7864d`.`colors` ;

CREATE TABLE IF NOT EXISTS `heroku_c287edf3bb7864d`.`colors` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  `deleted_at` TIMESTAMP NULL,
  `name` VARCHAR(100) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `heroku_c287edf3bb7864d`.`images`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `heroku_c287edf3bb7864d`.`images` ;

CREATE TABLE IF NOT EXISTS `heroku_c287edf3bb7864d`.`images` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  `deleted_at` TIMESTAMP NULL,
  `image` VARCHAR(100) NULL,
  `product_id` BIGINT NULL,
  `color_id` BIGINT NULL,
  INDEX `product_id_idx` (`product_id` ASC) ,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) ,
  INDEX `color_id_idx` (`color_id` ASC) ,
  CONSTRAINT `image_product_id`
    FOREIGN KEY (`product_id`)
    REFERENCES `heroku_c287edf3bb7864d`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `color_id`
    FOREIGN KEY (`color_id`)
    REFERENCES `heroku_c287edf3bb7864d`.`colors` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `heroku_c287edf3bb7864d`.`carts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `heroku_c287edf3bb7864d`.`carts` ;

CREATE TABLE IF NOT EXISTS `heroku_c287edf3bb7864d`.`carts` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `total` DECIMAL NULL,
  `user_id` BIGINT NULL,
  `status` VARCHAR(100) BINARY NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  `deleted_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) ,
  INDEX `user_id_idx` (`user_id` ASC) ,
  CONSTRAINT `user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `heroku_c287edf3bb7864d`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `heroku_c287edf3bb7864d`.`cart_product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `heroku_c287edf3bb7864d`.`cart_product` ;

CREATE TABLE IF NOT EXISTS `heroku_c287edf3bb7864d`.`cart_product` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  `deleted_at` TIMESTAMP NULL,
  `sale_id` BIGINT NULL,
  `product_id` BIGINT NULL,
  `subtotal` DECIMAL NULL,
  `units` INT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) ,
  INDEX `product_id_idx` (`product_id` ASC) ,
  INDEX `sale_id_idx` (`sale_id` ASC) ,
  CONSTRAINT `sale_id`
    FOREIGN KEY (`sale_id`)
    REFERENCES `heroku_c287edf3bb7864d`.`carts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `product_id`
    FOREIGN KEY (`product_id`)
    REFERENCES `heroku_c287edf3bb7864d`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `heroku_c287edf3bb7864d`.`views`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `heroku_c287edf3bb7864d`.`views` ;

CREATE TABLE IF NOT EXISTS `heroku_c287edf3bb7864d`.`views` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT NOT NULL,
  `product_id` BIGINT NOT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  `deleted_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) ,
  INDEX `views_product_id_idx` (`product_id` ASC) ,
  INDEX `views_user_id_idx` (`user_id` ASC) ,
  CONSTRAINT `views_product_id`
    FOREIGN KEY (`product_id`)
    REFERENCES `heroku_c287edf3bb7864d`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `views_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `heroku_c287edf3bb7864d`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
